site_name: TTSL
repo_url: https://github.com/SEEDS-Group/TTSL
repo_name: SEEDS-Group/TTSL
edit_uri: edit/main/docs/
site_url: !ENV READTHEDOCS_CANONICAL_URL
strict: true
docs_dir: .
site_dir: ../site
exclude_docs: |
  lexer/

nav:
  - Home:
      - README.md
  - Language:
      - language/README.md
      - Common:
          - language/common/statements.md
          - language/common/packages.md
          - language/common/imports.md
          - language/common/types.md
          - language/common/expressions.md
          - language/common/comments.md
          - language/common/constants.md
          - language/common/data.md
          - language/common/functions.md
          - language/common/parameters.md
          - language/common/modifier.md
          - language/common/validity.md
          - language/common/aggregations.md
  - Development:
      - Call Graph Testing: development/call-graph-testing.md
      - Formatting Testing: development/formatting-testing.md
      - Generation Testing: development/generation-testing.md
      - Grammar Testing: development/grammar-testing.md
      - Partial Evaluation Testing: development/partial-evaluation-testing.md
      - Scoping Testing: development/scoping-testing.md
      - Typing Testing: development/typing-testing.md
      - Validation Testing: development/validation-testing.md

# Configuration of MkDocs & Material for MkDocs --------------------------------

theme:
  name: material
  logo: https://raw.githubusercontent.com/Safe-DS/.github/main/branding/safe-ds_logo_rounded.svg
  favicon: https://raw.githubusercontent.com/Safe-DS/.github/main/branding/safe-ds_logo_rounded.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: indigo
      accent: indigo

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: black
      accent: indigo
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.top

plugins:
  - glightbox
  - same-dir
  - search

markdown_extensions:
  # Admonitions
  - admonition
  - pymdownx.details

  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  # Diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # Footnotes
  - footnotes

  # Keys
  - pymdownx.keys

  # Icons & emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # Images
  - attr_list
  - md_in_html

  # Lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  # MathJax
  - pymdownx.arithmatex:
      generic: true

  # Permalinks
  - toc:
      permalink: true

extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
